### PR TITLE
added libpd.o Linux libpd shared object binary

### PR DESCRIPTION
**Pull request by mxa**
first steps towards Linux support

### CODE REVIEW

**Comment by NiallMoody** [comment]
From [issue #8](https://github.com/LibPdIntegration/LibPdIntegration/issues/8)  it sounds like you haven't got this working with Unity. I'm hesitant to accept a pull request that 1. sounds like it may be broken, and 2. that I'm not in a position to verify myself.

If you can confirm that the plugin is actually working on Linux I'll be happy to merge it.

**Comment by mxa** [comment]
I'll keep trying.

**Comment by brandflake11** [comment]
@mxa Did you ever get this working in Linux? I am working on a project and think it would be pretty cool to use libpd in Unity on Linux.

**Comment by mxa** [comment]
@brandflake11 nope, but we gained some more experiences meanwhile. Let's join forces and give it another stab.

**Comment by NiallMoody** [comment]
Oh, hey, I actually just added Linux binaries to the repo (contributed via email). I've not tested them myself, so let me know if you run into any issues.

I'll do a full release in the next couple of weeks once I've tidied up a few other bits and pieces.

**Pull request closed without merging**
