### PR TITLE
Apple Silicon Support

### PR DESCRIPTION
**Pull request by emurray2**
This PR addresses what's discussed in #35, #31, #27, and #21

### CODE REVIEW

**Comment by NiallMoody** [comment]
Thanks for this! This will be the last pull request I merge, as I no longer have the time or resources to maintain the project. Hopefully your PR at least means it will work on macs for a while longer.

**Comment by emurray2** [comment]
> Thanks for this! This will be the last pull request I merge, as I no longer have the time or resources to maintain the project. Hopefully your PR at least means it will work on macs for a while longer.

Anytime, happy to help and I understand 🙂! I apologize, but I realized when I changed the code it doesn't work on Windows machines. I'll need to test again and make another PR, or I could help maintain this if you like. Whatever is most convenient.

**Comment by NiallMoody** [comment]
Oh, that's weird. I tested it on my Windows machine before I merged it, and it seemed to work for me?

I really have no time anymore to maintain this project, so if you have an updated PR that is a vital bugfix I'd probably have to merge it without testing. I'm happy to transfer ownership of the project to yourself or someone else if you'd be willing to take over from me, though I understand that's a fairly big commitment.

**Comment by emurray2** [comment]
> Oh, that's weird. I tested it on my Windows machine before I merged it, and it seemed to work for me?
> 
> I really have no time anymore to maintain this project, so if you have an updated PR that is a vital bugfix I'd probably have to merge it without testing. I'm happy to transfer ownership of the project to yourself or someone else if you'd be willing to take over from me, though I understand that's a fairly big commitment.

I think it actually had something to do with my pd patch. I'm currently building the latest dll's for libpd to see if that fixes it. I'll keep you posted. Also I totally understand, I'm thankful you were able to merge this pull request still! I'm currently using this repo for a class right now and it's working great, so I thought I would contribute what I can to make it work for more people. I would love to take over and help as much as I can!

**Comment by NiallMoody** [comment]
Okay, cool. I'm busy until the end of the week, but I'll look into transferring ownership then. And thanks!

**Comment by emurray2** [comment]
> Okay, cool. I'm busy until the end of the week, but I'll look into transferring ownership then. And thanks!

Sounds great, thank you so much! I think this will be a good learning opportunity for me. And good luck with all your future endeavors! I'm grateful to be continuing all of your hard work on this repo!

**Pull request merged**
